ALTER TABLE `CustomerReturn`
    ADD COLUMN `requestKey` VARCHAR(128) NULL,
    ADD COLUMN `requestHash` CHAR(64) NULL,
    ADD COLUMN `manufacturerId` VARCHAR(191) NULL,
    ADD COLUMN `lifecycleStatus` VARCHAR(191) NOT NULL DEFAULT 'LEGACY_PROCESSED',
    ADD COLUMN `adminReviewerId` VARCHAR(191) NULL,
    ADD COLUMN `adminNotes` TEXT NULL,
    ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `originalNcmOrderId` INTEGER NULL,
    ADD COLUMN `ncmReturnOrderId` INTEGER NULL,
    ADD COLUMN `ncmDeliveryCharge` DOUBLE NULL,
    ADD COLUMN `ncmChargeSource` VARCHAR(32) NULL,
    ADD COLUMN `ncmChargePayer` VARCHAR(16) NOT NULL DEFAULT 'MERCHANT',
    ADD COLUMN `ncmSubmissionAttemptedAt` DATETIME(3) NULL,
    ADD COLUMN `ncmSubmissionError` TEXT NULL,
    ADD COLUMN `returnPickupStatus` VARCHAR(64) NULL,
    ADD COLUMN `returnPickupCompletedAt` DATETIME(3) NULL,
    ADD COLUMN `manufacturerReceivedAt` DATETIME(3) NULL,
    ADD COLUMN `inspectedAt` DATETIME(3) NULL,
    ADD COLUMN `inspectionResult` VARCHAR(64) NULL,
    ADD COLUMN `completedAt` DATETIME(3) NULL,
    MODIFY COLUMN `reason` TEXT NOT NULL,
    ADD UNIQUE INDEX `CustomerReturn_requestKey_key`(`requestKey`),
    ADD INDEX `CustomerReturn_ncmReturnOrderId_idx`(`ncmReturnOrderId`),
    ADD INDEX `CustomerReturn_lifecycleStatus_createdAt_idx`(`lifecycleStatus`, `createdAt`),
    ADD INDEX `CustomerReturn_orderId_lifecycleStatus_idx`(`orderId`, `lifecycleStatus`);

ALTER TABLE `OrderExchangeRequest`
    ADD COLUMN `ncmReturnCharge` DOUBLE NULL,
    ADD COLUMN `ncmReplacementCharge` DOUBLE NULL,
    ADD COLUMN `ncmTotalCharge` DOUBLE NULL,
    ADD COLUMN `ncmChargePayer` VARCHAR(16) NOT NULL DEFAULT 'MERCHANT',
    ADD COLUMN `replacementItems` JSON NULL,
    ADD COLUMN `priceDifference` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `replacementStockReservedAt` DATETIME(3) NULL,
    ADD COLUMN `replacementStockReleasedAt` DATETIME(3) NULL,
    ADD COLUMN `replacementStockConsumedAt` DATETIME(3) NULL;

CREATE TABLE `CustomerReturnEvent` (
    `id` VARCHAR(191) NOT NULL,
    `customerReturnId` VARCHAR(191) NOT NULL,
    `eventType` VARCHAR(64) NOT NULL,
    `fromStatus` VARCHAR(64) NULL,
    `toStatus` VARCHAR(64) NULL,
    `actorId` VARCHAR(191) NULL,
    `actorRole` VARCHAR(32) NULL,
    `reason` TEXT NULL,
    `metadata` JSON NULL,
    `idempotencyKey` VARCHAR(191) NOT NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE INDEX `CustomerReturnEvent_idempotencyKey_key`(`idempotencyKey`),
    INDEX `CustomerReturnEvent_customerReturnId_occurredAt_idx`(`customerReturnId`, `occurredAt`),
    INDEX `CustomerReturnEvent_eventType_occurredAt_idx`(`eventType`, `occurredAt`),
    PRIMARY KEY (`id`),
    CONSTRAINT `CustomerReturnEvent_customerReturnId_fkey` FOREIGN KEY (`customerReturnId`) REFERENCES `CustomerReturn`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ReturnExchangeNcmAttempt` (
    `id` VARCHAR(191) NOT NULL,
    `customerReturnId` VARCHAR(191) NULL,
    `exchangeRequestId` VARCHAR(191) NULL,
    `operation` VARCHAR(64) NOT NULL,
    `idempotencyKey` VARCHAR(191) NOT NULL,
    `attemptNumber` INTEGER NOT NULL,
    `requestUrl` VARCHAR(191) NOT NULL,
    `requestJson` JSON NULL,
    `responseJson` JSON NULL,
    `httpStatus` INTEGER NULL,
    `result` VARCHAR(32) NOT NULL,
    `errorCode` VARCHAR(191) NULL,
    `errorMessage` TEXT NULL,
    `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `finishedAt` DATETIME(3) NULL,
    UNIQUE INDEX `ReturnExchangeNcmAttempt_idempotencyKey_key`(`idempotencyKey`),
    INDEX `RtnExNcmAttempt_return_op_num_idx`(`customerReturnId`, `operation`, `attemptNumber`),
    INDEX `RtnExNcmAttempt_exchange_op_num_idx`(`exchangeRequestId`, `operation`, `attemptNumber`),
    INDEX `ReturnExchangeNcmAttempt_result_startedAt_idx`(`result`, `startedAt`),
    PRIMARY KEY (`id`),
    CONSTRAINT `ReturnExchangeNcmAttempt_customerReturnId_fkey` FOREIGN KEY (`customerReturnId`) REFERENCES `CustomerReturn`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `ReturnExchangeNcmAttempt_exchangeRequestId_fkey` FOREIGN KEY (`exchangeRequestId`) REFERENCES `OrderExchangeRequest`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;