CREATE TABLE `Notification` (
  `id` VARCHAR(191) NOT NULL,
  `idempotencyKey` VARCHAR(191) NULL,
  `notificationType` VARCHAR(64) NOT NULL DEFAULT 'GENERAL',
  `channel` VARCHAR(16) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `recipientName` VARCHAR(160) NULL,
  `recipientAddress` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NULL,
  `template` VARCHAR(120) NULL,
  `payload` JSON NULL,
  `provider` VARCHAR(64) NULL,
  `providerMessageId` VARCHAR(191) NULL,
  `priority` INTEGER NOT NULL DEFAULT 0,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `maxAttempts` INTEGER NOT NULL DEFAULT 5,
  `nextRetryAt` DATETIME(3) NULL,
  `lastAttemptAt` DATETIME(3) NULL,
  `queuedAt` DATETIME(3) NULL,
  `acceptedAt` DATETIME(3) NULL,
  `deliveredAt` DATETIME(3) NULL,
  `failedAt` DATETIME(3) NULL,
  `failureCode` VARCHAR(120) NULL,
  `failureReason` TEXT NULL,
  `claimToken` VARCHAR(64) NULL,
  `claimExpiresAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `Notification_idempotencyKey_key` (`idempotencyKey`),
  INDEX `Notification_status_nextRetryAt_idx` (`status`, `nextRetryAt`),
  INDEX `Notification_channel_status_createdAt_idx` (`channel`, `status`, `createdAt`),
  INDEX `Notification_provider_providerMessageId_idx` (`provider`, `providerMessageId`),
  INDEX `Notification_status_claimExpiresAt_idx` (`status`, `claimExpiresAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `NotificationAttempt` (
  `id` VARCHAR(191) NOT NULL,
  `notificationId` VARCHAR(191) NOT NULL,
  `attemptNumber` INTEGER NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `provider` VARCHAR(64) NULL,
  `providerMessageId` VARCHAR(191) NULL,
  `requestStartedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `requestFinishedAt` DATETIME(3) NULL,
  `httpStatus` INTEGER NULL,
  `providerStatus` VARCHAR(120) NULL,
  `providerErrorCode` VARCHAR(120) NULL,
  `providerErrorMessage` TEXT NULL,
  `failureCategory` VARCHAR(40) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `NotificationAttempt_notificationId_attemptNumber_key` (`notificationId`, `attemptNumber`),
  INDEX `NotificationAttempt_status_createdAt_idx` (`status`, `createdAt`),
  INDEX `NotificationAttempt_provider_providerMessageId_idx` (`provider`, `providerMessageId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `NotificationAttempt_notificationId_fkey` FOREIGN KEY (`notificationId`) REFERENCES `Notification` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `NotificationEvent` (
  `id` VARCHAR(191) NOT NULL,
  `notificationId` VARCHAR(191) NOT NULL,
  `eventType` VARCHAR(64) NOT NULL,
  `provider` VARCHAR(64) NULL,
  `providerEventId` VARCHAR(191) NULL,
  `providerMessageId` VARCHAR(191) NULL,
  `eventTimestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `payloadHash` VARCHAR(128) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `NotificationEvent_provider_providerEventId_key` (`provider`, `providerEventId`),
  INDEX `NotificationEvent_notificationId_eventTimestamp_idx` (`notificationId`, `eventTimestamp`),
  INDEX `NotificationEvent_provider_providerMessageId_idx` (`provider`, `providerMessageId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `NotificationEvent_notificationId_fkey` FOREIGN KEY (`notificationId`) REFERENCES `Notification` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `NotificationOutbox` (
  `id` VARCHAR(191) NOT NULL,
  `notificationId` VARCHAR(191) NOT NULL,
  `eventKey` VARCHAR(191) NOT NULL,
  `routingKey` VARCHAR(80) NOT NULL,
  `payload` JSON NOT NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `nextAttemptAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `leaseToken` VARCHAR(64) NULL,
  `leaseExpiresAt` DATETIME(3) NULL,
  `publishedAt` DATETIME(3) NULL,
  `lastError` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `NotificationOutbox_eventKey_key` (`eventKey`),
  INDEX `NotificationOutbox_delivery_idx` (`publishedAt`, `nextAttemptAt`, `leaseExpiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `NotificationOutbox_notificationId_fkey` FOREIGN KEY (`notificationId`) REFERENCES `Notification` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `IncomingSms` (
  `id` VARCHAR(191) NOT NULL,
  `provider` VARCHAR(64) NOT NULL DEFAULT 'SPARROW',
  `providerMessageId` VARCHAR(191) NULL,
  `fromNumber` VARCHAR(64) NOT NULL,
  `toShortCode` VARCHAR(64) NOT NULL,
  `keyword` VARCHAR(64) NULL,
  `text` VARCHAR(1600) NOT NULL,
  `payloadHash` VARCHAR(128) NOT NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `processingStatus` VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  `processedAt` DATETIME(3) NULL,
  `replyText` VARCHAR(160) NULL,
  `replyStatus` VARCHAR(32) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `IncomingSms_provider_providerMessageId_key` (`provider`, `providerMessageId`),
  INDEX `IncomingSms_provider_payloadHash_receivedAt_idx` (`provider`, `payloadHash`, `receivedAt`),
  INDEX `IncomingSms_processingStatus_receivedAt_idx` (`processingStatus`, `receivedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
