CREATE TABLE `AdminTwoFactorChallenge` (
  `id` VARCHAR(191) NOT NULL,
  `accountId` VARCHAR(191) NOT NULL,
  `targetPortal` VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
  `purpose` VARCHAR(32) NOT NULL DEFAULT 'ADMIN_LOGIN',
  `method` VARCHAR(16) NULL,
  `otpHash` VARCHAR(64) NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `maxAttempts` INTEGER NOT NULL DEFAULT 5,
  `resendCount` INTEGER NOT NULL DEFAULT 0,
  `expiresAt` DATETIME(3) NOT NULL,
  `lastSentAt` DATETIME(3) NULL,
  `verifiedAt` DATETIME(3) NULL,
  `consumedAt` DATETIME(3) NULL,
  `notificationId` VARCHAR(191) NULL,
  `requestIp` VARCHAR(64) NULL,
  `userAgentHash` VARCHAR(64) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `AdminTwoFactorChallenge_notificationId_key` (`notificationId`),
  INDEX `AdminTwoFactorChallenge_accountId_status_createdAt_idx` (`accountId`, `status`, `createdAt`),
  INDEX `AdminTwoFactorChallenge_status_expiresAt_idx` (`status`, `expiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `AdminTwoFactorChallenge_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `AuthAccount` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `AdminTwoFactorChallenge_notificationId_fkey` FOREIGN KEY (`notificationId`) REFERENCES `Notification` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;