export const ADMIN_ROUTE_PERMISSIONS = {
  "/finance": ["finance:dashboard_read"],
  "/treasury": ["finance:treasury_read"],
  "/assets": ["finance:assets_read"],
  "/partners": ["finance:captable_read", "finance:partnership_read"],
  "/expenses": ["expense:read", "expense:summary_read"],
  "/tax": ["finance:tax_report_read"],
  "/returns": ["returns:supplier_read", "returns:customer_read", "exchange:admin_read"],
  "/payables": ["finance:payables_read"],
  "/statements": ["finance:statements_read", "accounting:statements_read"],
  "/chart-of-accounts": ["accounting:coa_read"],
  "/journal-entries": ["accounting:journal_read"],
  "/general-ledger": ["accounting:ledger_read"],
  "/trial-balance": ["accounting:trial_balance_read"],
  "/fiscal-periods": ["accounting:fiscal_years_read", "accounting:period_toggle"],
  "/accounting-health": ["accounting:coa_read", "accounting:journal_read", "accounting:subledger_read"],
  "/add": ["product:create"],
  "/list": ["product:list_admin", "product:create", "product:update", "product:delete"],
  "/inventory": ["inventory:admin_read_all"],
  "/cogs": ["cogs:read"],
  "/special-offers": ["offer:list", "offer:create", "offer:update"],
  "/create-order": ["order:admin_create"],
  "/add-order": ["order:admin_create"],
  "/orders": ["order:list_admin"],
  "/order-assignments": ["assignment:admin_list"],
  "/delivery-monitor": ["delivery:admin_list", "delivery:settlements_read", "delivery:logs_read", "delivery:ncm_handoff_recover"],
  "/manufacturers": ["manufacturer:admin_list"],
  "/location-pricing": ["manufacturer:admin_update", "product:update"],
  "/manufacturer-inventory": ["inventory:admin_read_all", "inventory:admin_low_stock"],
  "/marketing-cards": ["marketing_card:admin_manage"],
  "/customers": ["customer:admin_list"],
  "/loyalty-levels": ["loyalty:level_manage"],
  "/categories": ["category:create", "category:delete", "subcategory:create", "subcategory:update", "color:create"],
  "/combo-bundles": ["combo_bundle:create", "combo_bundle:update", "combo_bundle:delete"],
  "/collaborations": ["collaboration:admin_manage", "collaboration:admin_reports_read"],
  "/reviews": ["review:admin_list"],
  "/story-letter-library": ["storyletter:admin_manage"],
  "/shipping": ["shipping:config_update"],
  "/access-control/users": ["access:admin_users_read", "access:marketing_users_read", "access:manufacturer_users_read", "access:customer_users_read"],
  "/access-control/roles": ["access:roles_read"],
  "/access-control/permissions": ["access:permissions_read"],
};

export const ADMIN_SECTION_PERMISSIONS = {
  catalog: ["product:create", "product:update", "product:delete", "category:create", "category:delete", "combo_bundle:create", "combo_bundle:update", "combo_bundle:delete", "collaboration:admin_manage", "collaboration:admin_reports_read", "subcategory:create", "color:create", "offer:list", "offer:create", "offer:update"],
  sales: ["order:list_admin", "order:admin_create"],
  supply: ["assignment:admin_list", "delivery:admin_list", "manufacturer:admin_list", "inventory:admin_read_all", "inventory:admin_low_stock"],
  marketing: ["marketing_card:admin_manage"],
  operations: ["inventory:admin_read_all", "cogs:read", "shipping:config_update"],
  finance: ["finance:dashboard_read", "finance:treasury_read", "finance:assets_read", "finance:partnership_read", "expense:read", "finance:tax_report_read", "returns:supplier_read", "finance:payables_read", "finance:statements_read"],
  accounting: ["accounting:coa_read", "accounting:journal_read", "accounting:ledger_read", "accounting:trial_balance_read", "accounting:fiscal_years_read", "accounting:subledger_read"],
  customers: ["customer:admin_list", "loyalty:level_manage", "review:admin_list", "storyletter:admin_manage"],
};
